### PR TITLE
Use factored out testing lib

### LINKED ISSUE #3579: Orphanded Helm Releases in CI
We've run into a case where timeouts in CI have left behind orphaned Helm releases. Cleanup didn't happen so the release and namespace for the PR (in some cases) is still present.

This has caused a problem of saturating the CI cluster which causes failed test runs on PRs.

In the short term I'm manually deleting some of the orphaned jobs to unblock CI. Next step is to create a script to automate cleanup.

If there are issues in CI still causing these we should fix them. Some of them (the ones I know of) have already been fixed.

/cc @kubernetes/charts-maintainers

### LINKED ISSUE #3772: [CI] Add check for deprecation
We should add a check that makes CI always fail if a PR makes changes to a deprecated chart.

### PR DESCRIPTION
**Pull request by unguiculus**
Updates CI to use refactored testing library.

Fixes #3772
Fixes #3579

### CODE REVIEW

**Comment by unguiculus** [comment]
Based on https://github.com/kubernetes-helm/chart-testing/pull/1

**Comment by unguiculus** [comment]
cc @kubernetes/charts-maintainers

File: test/helm-test-e2e.sh [hunk 1]
```diff
@@ -1,28 +1,41 @@
...
 
 # Install and initialize helm/tiller
-HELM_URL=https://storage.googleapis.com/kubernetes-helm
-HELM_TARBALL=helm-v2.8.2-linux-amd64.tar.gz
+readonly HELM_URL=https://storage.googleapis.com/kubernetes-helm
+readonly HELM_TARBALL=helm-v2.8.2-linux-amd64.tar.gz
 
-wget -q ${HELM_URL}/${HELM_TARBALL} -P ${WORKSPACE}
-tar xzfv ${WORKSPACE}/${HELM_TARBALL} -C ${WORKSPACE}
+wget -q "$HELM_URL/$HELM_TARBALL" -P "$WORKSPACE"
```
Comment (gianrubio) [inline test/helm-test-e2e.sh]: should this be packaged in the docker image?

File: .circleci/config.yml [hunk 2]
```diff
@@ -1,13 +1,13 @@
...
-       - checkout
-       - run:
-           name: install tools
-           command: test/circle/install.sh
-       - run: 
-           name: lint
-           command: test/circle/lint.sh
+  build:
+    docker:
+     - image: unguiculus/chart-testing
```
Comment (gianrubio) [inline .circleci/config.yml]: please pin a docker version

Comment (gianrubio) [reply .circleci/config.yml]: could you also add the source of this docker image in the git repo?

File: test/README.md [hunk 3]
```diff
@@ -27,19 +27,10 @@ The configuration of the Pull Request trigger is [in the config.json](https://gi
 
 This snippet tells Test Infra to run the [test/e2e.sh](https://github.com/kubernetes/charts/blob/master/test/e2e.sh)
 when testing is triggered on a pull request. The e2e.sh script will use the [Charts test image](https://github.com/kubernetes/charts/blob/master/test/Dockerfile)
-to run the [test/changed.sh](https://github.com/kubernetes/charts/blob/master/test/changed.sh) script. This script
+to run the [chart_test.sh](https://github.com/kubernetes-helm/chart-testing/blob/master/chart_test.sh) script. This script
```
Comment (gianrubio) [inline test/README.md:30]: this chart_test.sh link is broken

File: .circleci/config.yml (hunk 2 above)
Comment (gianrubio) [reply .circleci/config.yml]: never mind, I found it in the PR

File: test/README.md (hunk 3 above)
Comment (unguiculus) [reply test/README.md:30]: The links should work once https://github.com/kubernetes-helm/chart-testing/pull/1 is merged.

File: .circleci/config.yml (hunk 2 above)
Comment (unguiculus) [reply .circleci/config.yml]: The image will be updated to `gcr.io/kubernetes-charts-ci/test-image:v2.0.0` before the PR is merged.

File: test/helm-test-e2e.sh (hunk 1 above)
Comment (unguiculus) [reply test/helm-test-e2e.sh]: This script is for tests of a few whitelisted charts against Kubernetes master. It is not used in regular charts CI. I did not really do anything with that other than making ShellCheck happy. This should probably be tackled in a separate PR.

**Comment by unguiculus** [comment]
I bumped a few charts so they are tested and we can verify things work. This will be reverted before merging the PR.

**Comment by viglesiasce** [comment]
Removed the change to the grafana chart since it was failing the linter

**Comment by viglesiasce** [comment]
@unguiculus when is this going to be ready to merge? It looks good to me other than the changes to the charts.

**Comment by timstoop** [comment]
I think it still needs kubernetes-helm/chart-testing#1 to be merged before this one can be?

**Comment by unguiculus** [comment]
CircleCI should become green once #5847 is merged.

File: test/Dockerfile [hunk 4]
```diff
@@ -12,45 +12,19 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-FROM debian:8.5
+FROM gcr.io/kubernetes-charts-ci/chart-testing:v1.0.0
```
Comment (mattfarina) [inline test/Dockerfile]: Where is the source for this FROM? It's under our control which is why I'm curious.

Side note, I'm starting to ponder Quay because of the container image security scanning.

**Review by mattfarina — COMMENTED** [review]
On the whole this looks good. I still need to look at the charts testing repo.

File: test/Dockerfile (hunk 4 above)
Comment (unguiculus) [reply test/Dockerfile]: That's the image containing the new factored out testing stuff.

File: .circleci/config.yml [hunk 5]
```diff
@@ -21,9 +33,10 @@ jobs:
           command: test/repo-sync.sh
 workflows:
   version: 2
-  test:
+  lint:
     jobs:
-      - build
+      - lint-scripts
+      - lint-charts
```
Comment (mattfarina) [inline .circleci/config.yml:39]: Note: Since this name is changing from build the required tests for branch will need to change when this goes in.

**Review by mattfarina — COMMENTED** [review]
On the whole this looks good. I would like @viglesiasce or @prydonius to give it a thumbs up, too.
